import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";

const TermsConditions = () => {
  return (
    <div className="min-h-screen bg-background">
      <div className="container max-w-4xl mx-auto px-4 py-12">
        <Link to="/">
          <Button variant="ghost" className="mb-8">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Home
          </Button>
        </Link>

        <h1 className="text-4xl font-bold mb-2">Terms & Conditions</h1>
        <p className="text-muted-foreground mb-8">Last updated: December 2024</p>

        <div className="prose prose-invert max-w-none space-y-8">
          <section>
            <h2 className="text-2xl font-semibold mb-4">Agreement to Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              By accessing or using Weez.AI by Dexraflow, you agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use our services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Description of Service</h2>
            <p className="text-muted-foreground leading-relaxed">
              Weez.AI is an AI-powered document intelligence and marketing automation platform. We provide tools for processing documents, generating proposals, conducting research, and creating marketing content using artificial intelligence.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">User Accounts</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              To use our services, you must:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2">
              <li>Create an account with accurate information</li>
              <li>Maintain the security of your account credentials</li>
              <li>Be at least 18 years old or have parental consent</li>
              <li>Not share your account with others</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Acceptable Use</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              You agree not to:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2">
              <li>Use the service for illegal purposes</li>
              <li>Upload malicious content or malware</li>
              <li>Attempt to gain unauthorized access to our systems</li>
              <li>Interfere with or disrupt the service</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Use the service to generate harmful or misleading content</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Subscription & Payments</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              Our services are offered on a subscription basis:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2">
              <li>Subscriptions are billed monthly</li>
              <li>You may cancel at any time; access continues until the end of the billing period</li>
              <li>Refunds are handled on a case-by-case basis</li>
              <li>We reserve the right to change pricing with 30 days notice</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Intellectual Property</h2>
            <p className="text-muted-foreground leading-relaxed">
              You retain ownership of all content you upload. Content generated by our AI tools based on your inputs belongs to you. The Weez.AI platform, including its software, design, and branding, remains the property of Dexraflow.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Data Handling & AI</h2>
            <p className="text-muted-foreground leading-relaxed">
              <strong className="text-foreground">We do not retain your uploaded data.</strong> Files are processed in real-time and are not stored after processing. Furthermore, <strong className="text-foreground">we do not use your data to train our AI models</strong>. For full details, please review our{" "}
              <Link to="/privacy-policy" className="text-primary hover:underline">
                Privacy Policy
              </Link>
              .
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              Weez.AI is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the service. Our total liability is limited to the amount you paid for the service in the preceding 12 months.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">AI-Generated Content Disclaimer</h2>
            <p className="text-muted-foreground leading-relaxed">
              Content generated by our AI tools is provided for informational purposes. While we strive for accuracy, AI-generated content should be reviewed before use. You are responsible for verifying the accuracy and appropriateness of any AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Termination</h2>
            <p className="text-muted-foreground leading-relaxed">
              We may suspend or terminate your account if you violate these terms. You may terminate your account at any time by contacting us.
            </p>
          </section>

          <section className="bg-primary/10 border border-primary/20 rounded-lg p-6">
            <h2 className="text-2xl font-semibold mb-4">Account Deletion</h2>
            <p className="text-muted-foreground leading-relaxed">
              You can request complete deletion of your account and all associated data at any time by emailing us at{" "}
              <a href="mailto:support@dexraflow.com" className="text-primary hover:underline font-medium">
                support@dexraflow.com
              </a>
              . We will process your request within 30 days.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Changes to Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the new terms. We will notify you of significant changes via email or platform notification.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Contact Us</h2>
            <p className="text-muted-foreground leading-relaxed">
              If you have any questions about these Terms & Conditions, please contact us at{" "}
              <a href="mailto:support@dexraflow.com" className="text-primary hover:underline">
                support@dexraflow.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsConditions;
