import { motion } from "framer-motion";
import { Heart, MessageCircle, Repeat2, ThumbsUp, Sparkles, Mic, FileText, CheckCircle2 } from "lucide-react";

/**
 * Floating ambient cards rendered behind hero text.
 * - LinkedIn-style posts with reaction counts
 * - "Content generated" status cards
 * - Sage AI voice-interview chat bubbles
 * All slightly blurred + periodically floating to feel ambient, not distracting.
 */
const float = (dur: number, delay = 0, yRange = 18) => ({
  animate: {
    y: [0, -yRange, 0, yRange * 0.6, 0],
    rotate: [0, 0.6, 0, -0.6, 0],
  },
  transition: { duration: dur, delay, repeat: Infinity, ease: "easeInOut" as const },
});

const fadeCycle = (dur: number, delay = 0) => ({
  animate: { opacity: [0, 0.85, 0.85, 0] },
  transition: { duration: dur, delay, repeat: Infinity, ease: "easeInOut" as const, times: [0, 0.2, 0.8, 1] },
});

const LinkedInPost = ({
  name,
  role,
  text,
  reactions,
  comments,
  reposts,
}: {
  name: string;
  role: string;
  text: string;
  reactions: number;
  comments: number;
  reposts: number;
}) => (
  <div className="w-[280px] rounded-2xl border border-slate-900/10 bg-white/85 backdrop-blur-md shadow-xl shadow-blue-900/10 p-4">
    <div className="flex items-center gap-3">
      <div className="w-9 h-9 rounded-full bg-gradient-to-br from-blue-500 to-sky-400 flex items-center justify-center text-white font-bold text-xs">
        {name.split(" ").map((n) => n[0]).join("")}
      </div>
      <div>
        <div className="text-[13px] font-semibold text-slate-900 leading-tight">{name}</div>
        <div className="text-[11px] text-slate-500 leading-tight">{role}</div>
      </div>
      <div className="ml-auto text-[10px] text-slate-400">2h</div>
    </div>
    <p className="mt-3 text-[12px] text-slate-700 leading-snug line-clamp-3">{text}</p>
    <div className="mt-3 flex items-center gap-2 pt-2 border-t border-slate-100">
      <div className="flex -space-x-1">
        <span className="w-4 h-4 rounded-full bg-blue-600 flex items-center justify-center ring-2 ring-white">
          <ThumbsUp className="w-2 h-2 text-white" />
        </span>
        <span className="w-4 h-4 rounded-full bg-rose-500 flex items-center justify-center ring-2 ring-white">
          <Heart className="w-2 h-2 text-white" />
        </span>
      </div>
      <span className="text-[11px] text-slate-600 font-medium">{reactions} reactions</span>
      <span className="ml-auto text-[11px] text-slate-500 flex items-center gap-1">
        <MessageCircle className="w-3 h-3" /> {comments}
      </span>
      <span className="text-[11px] text-slate-500 flex items-center gap-1">
        <Repeat2 className="w-3 h-3" /> {reposts}
      </span>
    </div>
  </div>
);

const ContentGeneratedCard = ({ title, type }: { title: string; type: string }) => (
  <div className="w-[260px] rounded-2xl border border-slate-900/10 bg-gradient-to-br from-white/90 to-blue-50/80 backdrop-blur-md shadow-xl shadow-blue-900/10 p-4">
    <div className="flex items-center gap-2">
      <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-blue-600 to-sky-400 flex items-center justify-center">
        <Sparkles className="w-4 h-4 text-white" />
      </div>
      <div>
        <div className="text-[11px] uppercase tracking-wider text-blue-600 font-semibold">{type}</div>
        <div className="text-[12px] text-slate-900 font-medium">Generated by Weez</div>
      </div>
      <CheckCircle2 className="ml-auto w-4 h-4 text-emerald-500" />
    </div>
    <p className="mt-3 text-[12px] text-slate-700 leading-snug line-clamp-2">{title}</p>
    <div className="mt-3 flex items-center gap-1.5">
      <div className="h-1 flex-1 rounded-full bg-gradient-to-r from-blue-500 to-sky-400" />
      <span className="text-[10px] text-slate-500 font-medium">Ready</span>
    </div>
  </div>
);

const SageChatCard = () => (
  <div className="w-[300px] rounded-2xl border border-slate-900/10 bg-white/90 backdrop-blur-md shadow-xl shadow-blue-900/10 p-4">
    <div className="flex items-center gap-2 pb-2 border-b border-slate-100">
      <div className="w-7 h-7 rounded-full bg-gradient-to-br from-violet-500 to-blue-500 flex items-center justify-center">
        <Mic className="w-3.5 h-3.5 text-white" />
      </div>
      <div>
        <div className="text-[12px] font-semibold text-slate-900 leading-tight">Sage AI</div>
        <div className="text-[10px] text-slate-500 leading-tight">Weekly founder voice interview</div>
      </div>
      <span className="ml-auto w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
    </div>
    <div className="mt-3 space-y-2">
      <div className="text-[11px] text-slate-600 bg-slate-100 rounded-xl rounded-tl-sm px-3 py-2 max-w-[85%]">
        What wins shipped this week, and who did you sell to?
      </div>
      <div className="ml-auto text-[11px] text-white bg-gradient-to-r from-blue-600 to-sky-500 rounded-xl rounded-tr-sm px-3 py-2 max-w-[85%]">
        Closed 3 SaaS founders. New ICP: pre-seed B2B.
      </div>
      <div className="text-[11px] text-slate-600 bg-slate-100 rounded-xl rounded-tl-sm px-3 py-2 max-w-[85%] flex items-center gap-1.5">
        <FileText className="w-3 h-3 text-blue-500" /> Got it — updating your context.
      </div>
    </div>
  </div>
);

export const HeroFloatingCards = () => {
  return (
    <div className="absolute inset-0 pointer-events-none overflow-hidden" aria-hidden="true">
      {/* Soft blur + reduced opacity to keep text readable */}
      <div className="absolute inset-0" style={{ filter: "blur(1.5px)" }}>
        {/* Top-left LinkedIn post */}
        <motion.div
          className="absolute top-[8%] left-[3%] hidden md:block"
          {...float(9, 0)}
        >
          <motion.div {...fadeCycle(12, 0)}>
            <LinkedInPost
              name="Aanya Mehta"
              role="Founder · SaaS"
              text="We replaced our 4-person content team with Weez AI. 3 months in: leads up 312%."
              reactions={148}
              comments={32}
              reposts={18}
            />
          </motion.div>
        </motion.div>

        {/* Top-right Sage chat */}
        <motion.div
          className="absolute top-[6%] right-[2%] hidden md:block"
          {...float(10, 1.2)}
        >
          <motion.div {...fadeCycle(14, 1.2)}>
            <SageChatCard />
          </motion.div>
        </motion.div>

        {/* Mid-left content generated */}
        <motion.div
          className="absolute top-[42%] left-[5%] hidden lg:block"
          {...float(11, 0.6)}
        >
          <motion.div {...fadeCycle(13, 0.6)}>
            <ContentGeneratedCard
              type="LinkedIn Post"
              title="5 signals your ICP is shifting (and what to ship next quarter)"
            />
          </motion.div>
        </motion.div>

        {/* Mid-right LinkedIn post */}
        <motion.div
          className="absolute top-[44%] right-[4%] hidden lg:block"
          {...float(9.5, 1.8)}
        >
          <motion.div {...fadeCycle(15, 1.8)}>
            <LinkedInPost
              name="Rohan Kapoor"
              role="CEO · Dexraflow"
              text="Weez wrote, scheduled and posted this. I just hit approve from my phone."
              reactions={104}
              comments={21}
              reposts={9}
            />
          </motion.div>
        </motion.div>

        {/* Bottom-left content card */}
        <motion.div
          className="absolute bottom-[6%] left-[8%] hidden md:block"
          {...float(12, 2.4)}
        >
          <motion.div {...fadeCycle(14, 2.4)}>
            <ContentGeneratedCard
              type="Carousel"
              title="The founder's playbook: how we 4x'd inbound with zero ad spend"
            />
          </motion.div>
        </motion.div>

        {/* Bottom-right LinkedIn post */}
        <motion.div
          className="absolute bottom-[4%] right-[6%] hidden md:block"
          {...float(10.5, 0.9)}
        >
          <motion.div {...fadeCycle(13, 0.9)}>
            <LinkedInPost
              name="Priya Sharma"
              role="Marketing Lead"
              text="156 reactions on a post I didn't even write. Weez nailed our voice."
              reactions={156}
              comments={28}
              reposts={14}
            />
          </motion.div>
        </motion.div>
      </div>

      {/* Vignette to keep hero text crisp */}
      <div className="absolute inset-0 bg-gradient-to-b from-white/40 via-white/10 to-white/60" />
      <div
        className="absolute inset-0"
        style={{
          background:
            "radial-gradient(ellipse at center, rgba(255,255,255,0.75) 0%, rgba(255,255,255,0.25) 35%, rgba(255,255,255,0) 70%)",
        }}
      />
    </div>
  );
};

export default HeroFloatingCards;
